USE Bealtiful_Project
CREATE TABLE FORNECEDOR
(
	CNPJ						VARCHAR(14) NOT NULL,
	RAZAO_SOCIAL				NVARCHAR(50) NOT NULL,
	DATA_ABERTURA				DATE,
	ULTIMA_COMPRA				DATE NOT NULL DEFAULT GETDATE(),
	DATA_CADASTRO				DATE NOT NULL DEFAULT GETDATE(),
	SITUACAO_FORNECEDOR			CHAR NOT NULL DEFAULT 'A'
	CONSTRAINT PK_FORNECEDOR PRIMARY KEY (CNPJ)
);

CREATE TABLE CLIENTE
(
	CPF								VARCHAR(11) NOT NULL,
	NOME_CLIENTE					NVARCHAR(50) NOT NULL,
	DATA_NASCIMENTO					DATE NOT NULL,
	SEXO							CHAR NOT NULL,
	ULTIMA_COMPRA					DATE NOT NULL DEFAULT GETDATE(),
	DATA_CADASTRO					DATE NOT NULL DEFAULT GETDATE(),
	SITUACAO_CLIENTE				CHAR NOT NULL DEFAULT 'A'
	CONSTRAINT PK_CLIENTE PRIMARY KEY (CPF)
);

CREATE TABLE PRODUTO
(
	CODIGO_BARRAS					NUMERIC(12) IDENTITY(789661700001,1) NOT NULL,
	NOME_PRODUTO					NVARCHAR(20) NOT NULL,
	VALOR_VENDA						NUMERIC(5,2) NOT NULL,
	ULTIMA_VENDA					DATE NOT NULL DEFAULT GETDATE(),
	DATA_CADASTRO					DATE NOT NULL DEFAULT GETDATE(),
	SITUACAO_PRODUTO				CHAR NOT NULL DEFAULT 'A',
	CONSTRAINT PK_CODIGO_BARRAS PRIMARY KEY (CODIGO_BARRAS)
);

CREATE TABLE COMPRA 
(
	CODIGO_COMPRA					NUMERIC(5,0) IDENTITY(1,1) NOT NULL,
	DATA_COMPRA						DATE NOT NULL DEFAULT GETDATE(),
	VALOR_TOTAL						NUMERIC(7,2) NOT NULL,
	CNPJ_FORNECEDOR					VARCHAR(14) NOT NULL,
	CONSTRAINT PK_CODIGO_COMPRA PRIMARY KEY (CODIGO_COMPRA),
	CONSTRAINT FK_FORNECEDOR_COMPRA FOREIGN KEY (CNPJ_FORNECEDOR) REFERENCES FORNECEDOR(CNPJ)
);

CREATE TABLE MATERIA_PRIMA
(
	CODIGO_MATERIA_PRIMA			VARCHAR(6) NOT NULL,
	NOME_MATERIA_PRIMA				NVARCHAR(30) NOT NULL,
	ULTIMA_COMPRA					DATE NOT NULL DEFAULT GETDATE(),
	DATA_CADASTRO					DATE NOT NULL DEFAULT GETDATE(),
	SITUACAO_MATERIA_PRIMA			CHAR NOT NULL DEFAULT 'A'
	CONSTRAINT PK_MATERIA_PRIMA PRIMARY KEY(CODIGO_MATERIA_PRIMA)
);


CREATE TABLE VENDA_CLIENTE
(
	CODIGO_VENDA					NUMERIC(5,0) IDENTITY(1,1) NOT NULL,
	DATA_VENDA						DATE NOT NULL DEFAULT GETDATE(),
	VALOR_TOTAL						NUMERIC(7,2) NOT NULL,
	CPF_CLIENTE						VARCHAR(11) NOT NULL
	CONSTRAINT PK_VENDA PRIMARY KEY (CODIGO_VENDA),
	CONSTRAINT FK_VENDA_CLIENTE FOREIGN KEY (CPF_CLIENTE) REFERENCES CLIENTE(CPF)
);

CREATE TABLE ITEM_COMPRA
(
	QUANTIDADE							NUMERIC(5,2) NOT NULL,
	VALOR_UNITARIO						NUMERIC(5,2) NOT NULL,
	TOTAL_ITEM							NUMERIC(6,2) NOT NULL,
	ITEM_COMPRA_CODIGO_COMPRA			NUMERIC(5,0) NOT NULL,
	ITEM_COMPRA_CODIGO_MATERIA_PRIMA	VARCHAR(6) NOT NULL​,
	CONSTRAINT ITEM_COMPRA_CODIGO_COMPRA FOREIGN KEY(ITEM_COMPRA_CODIGO_COMPRA) REFERENCES COMPRA(CODIGO_COMPRA),
	CONSTRAINT ITEM_COMPRA_CODIGO_MATERIA_PRIMA	FOREIGN KEY (ITEM_COMPRA_CODIGO_MATERIA_PRIMA) REFERENCES MATERIA_PRIMA(CODIGO_MATERIA_PRIMA)
);

CREATE TABLE PRODUCAO
(
	CODIGO_PRODUCAO					NUMERIC(5,0) IDENTITY(1,1) NOT NULL,
	DATA_PRODUCAO					DATE NOT NULL DEFAULT GETDATE(),
	QUANTIDADE						NUMERIC(5,2) NOT NULL,
	CODIGO_BARRAS_PRODUTO			NUMERIC(12) NOT NULL,
	CONSTRAINT PK_PRODUCAO PRIMARY KEY (CODIGO_PRODUCAO),
	CONSTRAINT FK_PRODUTO_PRODUCAO FOREIGN KEY (CODIGO_BARRAS_PRODUTO) REFERENCES PRODUTO(CODIGO_BARRAS)
);

CREATE TABLE ITEM_PRODUCAO
(	
	CODIGO_PRODUCAO					NUMERIC(5,0) NOT NULL,
	CODIGO_MATERIA_PRIMA			NUMERIC(4,0) NOT NULL,
	QUANTIDADE_MATERIA_PRIMA		NUMERIC(5,2) NOT NULL,
	CONSTRAINT PK_ITEM_PRODUCAO PRIMARY KEY (CODIGO_PRODUCAO),
	CONSTRAINT FK_ITEM_PRODUCAO FOREIGN KEY (CODIGO_PRODUCAO) REFERENCES PRODUCAO(CODIGO_PRODUCAO)
);

CREATE TABLE ITEM_VENDA
(
	ITEM_VENDA_CODIGO_VENDA				NUMERIC(5,0) NOT NULL,
	ITEM_VENDA_CODIGO_BARRAS_PRODUTO	NUMERIC(12) NOT NULL,
	QUANTIDADE							NUMERIC(3,0) NOT NULL,
	TOTAL_ITEM							NUMERIC(6,2) NOT NULL,
	VALOR_UNITARIO						NUMERIC(5,2) NOT NULL​,
	CONSTRAINT FK_VENDA_ITEM_VENDA_CODIGO_VENDA FOREIGN KEY (ITEM_VENDA_CODIGO_VENDA) REFERENCES VENDA_CLIENTE(CODIGO_VENDA),
	CONSTRAINT FK_CODIGO_BARRAS_ITEM_VENDA_CODIGO_VENDA FOREIGN KEY (ITEM_VENDA_CODIGO_BARRAS_PRODUTO) REFERENCES PRODUTO(CODIGO_BARRAS)
);

create table RISCO
(
	CPF_CLIENTE							VARCHAR(11) NOT NULL
	CONSTRAINT PK_RISCO			PRIMARY KEY(CPF_CLIENTE),
	CONSTRAINT FK_RISCO FOREIGN KEY (CPF_CLIENTE) REFERENCES CLIENTE(CPF)
);

CREATE TABLE BLOQUEADO
(
	CNPJ_FORNECEDOR						VARCHAR(14) NOT NULL​
	CONSTRAINT PK_BLOQUEADO	PRIMARY KEY(CNPJ_FORNECEDOR),
	CONSTRAINT FK_BLOQUEADO FOREIGN KEY (CNPJ_FORNECEDOR) REFERENCES FORNECEDOR(CNPJ)
);
​
----------------------------------------------------------------------------------------------------------------------------------------------------------

DROP TABLE CLIENTE
DROP TABLE COMPRA
DROP TABLE FORNECEDOR
DROP TABLE MATERIA_PRIMA
DROP TABLE PRODUTO
DROP TABLE ITEM_VENDA
DROP TABLE ITEM_PRODUCAO
DROP TABLE PRODUCAO

----------------------------------------------------------------------------------------------------------------------------------------------------------

SELECT * FROM FORNECEDOR
SELECT * FROM PRODUTO
SELECT * FROM CLIENTE
SELECT * FROM MATERIA_PRIMA

----------------------------------------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE INSERIR_FORNECEDOR_PROC
	@CNPJ VARCHAR(14),
	@RAZAO_SOCIAL NVARCHAR(50), 
	@DATA_ABERTURA DATE
AS
BEGIN	
	INSERT INTO FORNECEDOR (CNPJ, RAZAO_SOCIAL, DATA_ABERTURA)
	VALUES (@CNPJ, @RAZAO_SOCIAL, @DATA_ABERTURA)	
END
----------------------------------------------------------------------------------------------------------------------------------------------------------
CREATE PROCEDURE INSERIR_CLIENTE_PROC
	@CPF VARCHAR(11),
	@NOME_CLIENTE NVARCHAR(50),
	@DATA_NASCIMENTO DATE,
	@SEXO CHAR
AS
BEGIN
	INSERT INTO CLIENTE (CPF, NOME_CLIENTE, DATA_NASCIMENTO, SEXO)
	VALUES (@CPF, @NOME_CLIENTE, @DATA_NASCIMENTO, @SEXO)
END
----------------------------------------------------------------------------------------------------------------------------------------------------------
CREATE PROCEDURE INSERIR_PRODUTO_PROC
	@NOME_PRODUTO NVARCHAR(20),
	@VALOR_VENDA NUMERIC(5,2)
AS
BEGIN
	INSERT INTO PRODUTO (NOME_PRODUTO, VALOR_VENDA)
	VALUES(@NOME_PRODUTO, @VALOR_VENDA)
END
----------------------------------------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE INSERIR_COMPRA_PROC
	@VALOR_TOTAL NUMERIC(7,2),
	@CNPJ_FORNECEDOR VARCHAR(14)
AS
BEGIN
	INSERT INTO COMPRA (VALOR_TOTAL, CNPJ_FORNECEDOR)
	VALUES(@VALOR_TOTAL, @CNPJ_FORNECEDOR)
END
----------------------------------------------------------------------------------------------------------------------------------------------------------
CREATE PROCEDURE INSERIR_MATERIA_PRIMA_PROC
	@CODIGO_MATERIA_PRIMA VARCHAR(6),
	@NOME_MATERIA_PRIMA NVARCHAR(30)
AS 
BEGIN
	INSERT INTO MATERIA_PRIMA(CODIGO_MATERIA_PRIMA, NOME_MATERIA_PRIMA)
	VALUES (@CODIGO_MATERIA_PRIMA, @NOME_MATERIA_PRIMA)
END
----------------------------------------------------------------------------------------------------------------------------------------------------------
CREATE PROCEDURE INSERIR_VENDA_CLIENTE_PROC
	@VALOR_TOTAL NUMERIC(7,2),
	@CPF_CLIENTE VARCHAR(11)
AS
BEGIN
	INSERT INTO VENDA_CLIENTE(VALOR_TOTAL, CPF_CLIENTE)
	VALUES (@VALOR_TOTAL, @CPF_CLIENTE)
END
----------------------------------------------------------------------------------------------------------------------------------------------------------
CREATE PROCEDURE INSERIR_ITEM_COMPRA_PROC
	@QUANTIDADE NUMERIC(5,2),
	@VALOR_UNITARIO NUMERIC(5,2),
	@TOTAL_ITEM NUMERIC(6,2),
	@ITEM_COMPRA_CODIGO_COMPRA NUMERIC(5,0),
	@ITEM_COMPRA_CODIGO_MATERIA_PRIMA VARCHAR(6)
AS
BEGIN
	INSERT INTO ITEM_COMPRA(QUANTIDADE, VALOR_UNITARIO, TOTAL_ITEM, ITEM_COMPRA_CODIGO_COMPRA, ITEM_COMPRA_CODIGO_MATERIA_PRIMA)
	VALUES(@QUANTIDADE, @VALOR_UNITARIO, @TOTAL_ITEM, @ITEM_COMPRA_CODIGO_COMPRA, @ITEM_COMPRA_CODIGO_MATERIA_PRIMA)
END
----------------------------------------------------------------------------------------------------------------------------------------------------------
CREATE PROCEDURE INSERIR_PRODUCAO_PROC 
	@QUANTIDADE NUMERIC(5,2),
	@CODIGO_BARRAS_PRODUTO NUMERIC(12)
AS
BEGIN
	INSERT INTO PRODUCAO(QUANTIDADE, CODIGO_BARRAS_PRODUTO)
	VALUES(@QUANTIDADE, @CODIGO_BARRAS_PRODUTO)
END
----------------------------------------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE INSERIR_ITEM_PRODUCAO_PROC
	@CODIGO_PRODUCAO NUMERIC(5,0),
	@CODIGO_MATERIA_PRIMA NUMERIC(4,0),
	@QUANTIDADE_MATERIA_PRIMA NUMERIC(5,2)
AS
BEGIN
	INSERT INTO ITEM_PRODUCAO(CODIGO_PRODUCAO, CODIGO_MATERIA_PRIMA, QUANTIDADE_MATERIA_PRIMA)
	VALUES (@CODIGO_PRODUCAO, @CODIGO_MATERIA_PRIMA, @QUANTIDADE_MATERIA_PRIMA)
END
----------------------------------------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE INSERIR_ITEM_VENDA_PROC
	@ITEM_VENDA_CODIGO_VENDA NUMERIC(5,0),
	@ITEM_VENDA_CODIGO_BARRAS_PRODUTO NUMERIC(12),
	@QUANTIDADE	NUMERIC(3,0),
	@TOTAL_ITEM	NUMERIC(6,2),
	@VALOR_UNITARIO NUMERIC(5,2)
AS
BEGIN
	INSERT INTO ITEM_VENDA(ITEM_VENDA_CODIGO_VENDA, ITEM_VENDA_CODIGO_BARRAS_PRODUTO, QUANTIDADE, TOTAL_ITEM, VALOR_UNITARIO)
	VALUES (@ITEM_VENDA_CODIGO_VENDA, @ITEM_VENDA_CODIGO_BARRAS_PRODUTO, @QUANTIDADE, @TOTAL_ITEM, @VALOR_UNITARIO)
END
----------------------------------------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE INSERIR_RISCO
	@CPF_CLIENTE VARCHAR(11)
AS
BEGIN
	INSERT INTO RISCO(CPF_CLIENTE)
	VALUES (@CPF_CLIENTE)
END
----------------------------------------------------------------------------------------------------------------------------------------------------------

CREATE PROCEDURE INSERIR_BLOQUEADO
	@CNPJ_FORNECEDOR VARCHAR(14)
AS
BEGIN
	INSERT INTO BLOQUEADO(CNPJ_FORNECEDOR)
	VALUES (@CNPJ_FORNECEDOR)
END
----------------------------------------------------------------------------------------------------------------------------------------------------------